### ISSUE TITLE
Configuration error with .less mimetype definition

### ISSUE THREAD

**Issue by bmillerbma** [Azure/azure-iot-remote-monitoring#69] opened 2015-11-04 03:44 UTC
IIS Express places an applicationhost.config file in the solution directory (.svn/applicationhost.config) with the .less mimetype arleady defined.  The addition of the .less mimetype in the web.config file throws a configuration error unless the entry is first removed.  Please see:

https://github.com/bmillerbma/azure-iot-remote-monitoring/commit/6f23f98df11e392e60d65186442a52e7bc1d99c6

**Comment by azaslonov** [comment] 2015-11-07 06:11
Hi bmillerbma, this issue was fixed by this commit: https://github.com/Azure/azure-iot-remote-monitoring/commit/3ef4feae664e3f0a4fe9a8b2645b015465ba7ab0

**Closed by azaslonov** 2015-11-07 06:11 UTC

**Comment by bmillerbma** [comment] 2015-11-07 11:59
I believe it was commit https://github.com/Azure/azure-iot-remote-monitoring/commit/3ef4feae664e3f0a4fe9a8b2645b015465ba7ab0 that caused the issue.  You need the `<remove />` element before the add.

![less](https://cloud.githubusercontent.com/assets/15265832/11015051/e5aac09e-851c-11e5-8f7a-cf8b6343d739.png)

**Comment by azaslonov** [comment] 2015-11-09 17:58
Hi bmillerbma, can you please try to grab the latest version and see if the issue is reproduced?
