### ISSUE TITLE
Error upgrading deployment to latest revision.

### ISSUE THREAD

**Issue by networkfusion** [Azure/azure-iot-remote-monitoring#403] opened 2016-11-15 22:56 UTC
After a fresh deploy using the build script (which worked) of revision 8894834284ea2ff1a83f8ebe8f798bcf5b4078c1 , it is not possible to upgrade the instance using the build script. doing so causes the fatal error:

New-AzureRmResourceGroupDeployment : 22:42:07 - Error: Code=InvalidTemplate; Message=Deployment template validation
failed: 'The provided value for the template parameter 'webWorkerSize' at line '126' and column '27' is not valid.'.

I have a feeling it might be related to the changes made in b4722257f09620c9e8aaec2d238f64bbe3087e17 as it deployed successfully previous to this. Also of note that when I tried upgrading from b4722257f09620c9e8aaec2d238f64bbe3087e17 to 8894834284ea2ff1a83f8ebe8f798bcf5b4078c1, I was unable to do so as it was giving an error that it couldn't find the correct resource and wouldn't create a new one.

**Comment by networkfusion** [comment] 2016-11-16 23:02
I should clarify that this seems to be a problem with the RemoteMonitoringMapKey.json template.

**Comment by xzsheng** [comment] 2016-11-23 11:05
Hi networkfusion, we drafted a fix for this issue on branch 'issue403fix'. Could you please help us to verify if it work for you? Thanks.

**Comment by networkfusion** [comment] 2016-11-23 12:54
Deploying now...

just of note, on a fresh deployment I am getting some errors when creating the AD app but it seems to be non blocking, e.g.:

`Invoke-RestMethod : {"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"Cannot convert a
primitive value to the expected type 'Edm.Guid'. See the inner exception for more details."}}}
At F:\Robin\Source\Repos\SurfaceNetIoTHub\Common\Deployment\DeploymentLib.ps1:783 char:19
+ ...   $result = Invoke-RestMethod -Method "POST" -Uri $uri -Headers @{"Au ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

**Comment by networkfusion** [comment] 2016-11-23 14:43
I can confirm that this fixes the issue with WorkerSize. Is there a route cause to this? If so, is there some documentation I should keep an eye on so that I can hopefully resolve similar problems in future?

Thanks.

**Comment by xzsheng** [comment] 2016-11-24 03:08
The root cause is one field (WorkerSize) of the server farm property retrieved by PowerShell cmdlet was changed from integer to string. In this fix, we are going to switch to other field (WorkerSizeId).

For more details, please check our commit:
https://github.com/Azure/azure-iot-remote-monitoring/commit/696b7d779805da601fafa1824d5c6da8a43b4b13

**Comment by xzsheng** [comment] 2016-11-24 09:26
This code change was merged into master branch, and the hotfix branch was deleted. For the commit detail, please check https://github.com/Azure/azure-iot-remote-monitoring/commit/39cfe22dde8318d2f8af4eafdc0f5bede5a2269d.

**Closed** 2016-11-24 12:06 UTC
