### ISSUE TITLE
Refresh issues : Telemetry history and device parameters

### ISSUE THREAD

**Issue by monteil** [Azure/azure-iot-remote-monitoring#5] opened 2015-10-08 16:17 UTC
Hello,

After deploying the "Remote Monitoring" preconfigured solution, the dashboard is displayed without any data in the 'Telemetry History' & 'telemetry grid' panel. I sometime get the following error in a popup : 'Unable to retrieve device telemetry from service'. Other data are correct, including alerts.

I assume this is due to a timeout issue as all the telemetry data are properly generated in the blob storage ('devicetelemetry' container).
I have tried to increase the refreshMilliseconds parameter to 9000 (file _DashboardDevicePane.cshtml ) and restarted the server, but it did not solved the issue. 
Note that I connect from a rather slow connection and my solution is deployed in 'North Europe'.

Other issue: when editing and updating a device parameter (such as manufacturer name or gps coordinates) the update is applyied for a few minutes and then the parameters are restored to their initial values.

Thank you for your help. 
By the way, this application is great and really promising!

Stephane

**Comment by stevehoberecht** [comment] 2015-10-08 16:34
Hi Stephane,

Thank you for exploring this preconfigured solution and your feedback.

We are actively investigating a similar issue with another customer regarding the chart data not displaying.  I will follow up with you directly to get more details.

Regarding the device properties resetting and overwriting changes you make in the device portal.  This is currently expected behavior due to how we've implemented the device simulators.  When the device simulator starts (the web job is re-started, or the device is stopped/started via commands), the first thing it does is send its device property data.  We automatically write this into the device registry store (Doc DB).  We do not do any checking to see if there's any conflicts with service-side changes.  If you have specific thoughts about how you'd like this to work, please let me know.

**Comment by monteil** [comment] 2015-10-08 20:15
Hi Steve,

Thanks for the quick reply. Let me know if I may be of any help to reproduce the first case (chart data undisplayed).
About the device properties, I better understand now the behavior in relation with to the simulator logic. From a business perspective, the benefits of keeping the device attributes updates would be to be able to personalize a demo for a specific customer, with simulated devices displayed on local map and friendly names. I will do a demo tomorrow to a potentiel customer in France and I wanted to prepare something like that. This is already a great tool to show the potential of the IoT Suite.
Thanks.

**Comment by stevehoberecht** [comment] 2015-10-09 02:33
Hi Stephane,

Are you starting/stopping your webjob (simulators) frequently?  I’m wondering if you are thinking about building the demo, running the simulator only during the demo, then stopping it when not in use?

Thanks,
Steve

**Comment by ermhawi** [comment] 2015-10-09 06:28
Hi,

I had the same problem that the telemetry history did not show up. When debugging it I realized that it was parsing of strings into double types that failed. If I replace:

  double.TryParse(value, out doubleValue);

with: 

  double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out doubleValue);

everywhere the parsing is made in the code then it works. I think it has something to do with which language your operating system if configured to use. I have swedish on my computer and it expects doubles in strings to be presented with a comma ',' and not with a dot '.'

**Comment by monteil** [comment] 2015-10-09 12:20
Hello,

Hakan is right about the telemetry history display, : A quick workaround is to set the web browser prefered language to English and then the charts are displayed and updated properly.

About the device parameter overwriting, I confirm I have restarted the webjobs yesterday several time, causing this behavior. I was able to run a personnazied demo today by avoiding to restart the service after updating the device parameters (+ web browser language to English).

Thanks.

**Comment by stevehoberecht** [comment] 2015-10-09 16:54
Yes, thank you Hakan and Stephane.  We are testing this fix and some other localization issues we found and will push the changes out soon.

Thanks!
Steve

**Comment by jamesweb-ms** [comment] 2015-10-20 01:20
Please give the October-Integration branch a try.  These issues should be fixed there now.

**Comment by jamesweb-ms** [comment] 2015-11-02 18:50
There was also a backend service issue that was causing these issue.  That should now be resolve.  Please try the october-integration branch and let us know if you still see these issues.

**Closed by jamesweb-ms** 2015-11-02 18:50 UTC
