### ISSUE TITLE
After Cloud Deployment, Local LiveDebugging

### ISSUE THREAD

**Issue by LeonardBae** [Azure/azure-iot-remote-monitoring#176] opened 2016-06-01 02:21 UTC
previously, I did local deployment and Live Debugging on local.
and it was well.
but, recently,  I have a problem to Live Debugging.
I completed cloud deployment. (build.cmd cloud debug XXXXX(resource name))
and I tried to Live Debugging on local.
but, it does not working on local.
(Web, Web.job state configure to stop 
and swap "local.config.user" to "xxxxx(resource name).config.user" ConfigurationProvider.cs)
how to local live debugging under conditions cloud deployment.

**Comment by jtanner-msft** [comment] 2016-06-01 22:53
Hi Leonard,

  It sounds like you would like to use Visual Studio to debug a deployment, and if that is the case then I would suggest you continue to follow the local deployment instructions listed here:

  https://github.com/Azure/azure-iot-remote-monitoring/blob/master/Docs/local-deployment.md 
  
  Please use this approach to debug any code changes as you modified the projects behavior to meet your needs.  Once it is working as you wish locally you can then switch to a full cloud deployment and have those services fully running in Azure.

  As you’ve discovered attempting to swap the ‘cloud’ deployment .user config files for a local deployment to debug in Visual Studio does not work.  This is expected behavior and by design.

  Once you have deployed the services into the cloud if you need additional diagnostics or logging to troubleshoot a problem while the service is running, you might want to review this article which talks about Enabling Azure Diagnostics in Azure Cloud Services:
  https://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-diagnostics/ 

  I hope that helps.  Please let me know if you have any other questions, on this topic or if we can close this issue.

~Jonathan

**Comment by jtanner-msft** [comment] 2016-06-06 22:06
Not having heard anything else, so closing the issue.  Please re-open if you need additional assistance.

**Closed by jtanner-msft** 2016-06-06 22:06 UTC
Labels: help wanted
